dist: xenial

language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - nightly

env:
  matrix:
    - CLICK="click>=3,<4"
    - CLICK="click>=4,<5"
    - CLICK="click>=5,<6"
    - CLICK="click>=6,<7"
    - CLICK="click>=7,<8"
    - CLICK="git+https://github.com/pallets/click.git"

install:
  - pip install "${CLICK}"
  - pip install -e .\[dev\]

script:
  - pytest tests --cov pyin --cov-report term-missing

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
