dist: xenial

language: python

cache: pip

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - nightly

install:
  - pip install .\[dev\]

script:
  - pytest tests --cov pyin --cov-report term-missing

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
