language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install -e .\[dev\]

script:
  - py.test tests --cov pyin --cov-report term-missing

after_success:
  - coveralls
