dist: xenial

language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - nightly

install:
  - pip install -e .\[dev\]

script:
  - py.test tests --cov pyin --cov-report term-missing

after_success:
  - coveralls || echo "!! intermittent coveralls failure"
